### ISSUE TITLE
Javascript Regex Free Course Alternative

### ISSUE THREAD

**Issue by leandrosimoes** [codedamn/fullstack-learning-path#1]
Any plans to put that on the course base?

**Comment by pranavmandava** [comment]
We will be adding a section on Regular Expressions in the upcoming weeks. You can refer to the two resources for understanding / learning Regex 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp

https://regexr.com/

https://regexlearn.com/learn/regex101

**Comment by mehulmpt** [comment]
Regular expressions course is now available: https://codedamn.com/learning-paths/fullstack
